"""Generate FIGURES_MANIFEST.md — the exact \\includegraphics line per figure.

    python figures/make_manifest.py

Widths are read back out of the rendered PDFs rather than assumed, so the
include fractions cannot drift away from what was actually drawn (FIGURES.md
§2). Run this after any render.
"""

from __future__ import annotations

import re
from pathlib import Path

FIGURE_DIR = Path(__file__).resolve().parent

# includes.tex:20 — a4paper, hmargin=2.8cm on a 21.0cm page.
TEXT_WIDTH_CM = 21.0 - 2 * 2.8

# A tight bounding box trims a little off the authored width; anything within
# this of the text block is treated as a full-width figure.
FULL_WIDTH_TOLERANCE_CM = 0.9

LABELS = {
    "fig_exposure_by_arm": "fig:exposure-by-arm",
    "fig_flagged_vs_corrected": "fig:flagged-vs-corrected",
    "fig_scenario_inversion": "fig:scenario-inversion",
    "fig_harm_averted": "fig:harm-averted",
    "fig_refinement_lattice": "fig:refinement-lattice",
    "fig_five_arm_summary": "fig:five-arm-summary",
    "fig_friction_window": "fig:friction-window",
    "fig_anchorfree_certificate": "fig:anchorfree-certificate",
    "fig_gamma_independence": "fig:gamma-independence",
}


def pdf_width_cm(path: Path) -> float | None:
    data = path.read_bytes()
    m = re.search(
        rb"/MediaBox\s*\[\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)", data
    )
    if not m:
        return None
    width_pt = float(m.group(3)) - float(m.group(1))
    return width_pt / 72.0 * 2.54


def include_spec(width_cm: float) -> tuple[str, str]:
    if width_cm >= TEXT_WIDTH_CM - FULL_WIDTH_TOLERANCE_CM:
        return "\\textwidth", f"upscaled {TEXT_WIDTH_CM / width_cm:.3f}x"
    frac = width_cm / TEXT_WIDTH_CM
    return f"{frac:.2f}\\textwidth", "natural size"


# Which renderer draws which figure. A figure is stale if it is older than the
# module that draws it, than the data module every results figure is
# transcribed from, or than the shared style.
RENDERED_BY = {
    "render_results.py": [
        "fig_exposure_by_arm", "fig_flagged_vs_corrected", "fig_scenario_inversion",
        "fig_harm_averted", "fig_refinement_lattice", "fig_five_arm_summary",
    ],
    "render_theory.py": [
        "fig_friction_window", "fig_anchorfree_certificate", "fig_gamma_independence",
    ],
    "render_intro.py": ["fig_enforcement_point"],
}

# Sources every figure depends on regardless of which module draws it.
COMMON_SOURCES = ("science_data.py", "thesis_style.py")


def sources_for(stem: str) -> list[Path]:
    """The files a given figure is drawn from, that exist on disk."""
    out = [FIGURE_DIR / c for c in COMMON_SOURCES]
    for renderer, stems in RENDERED_BY.items():
        if stem in stems:
            out.append(FIGURE_DIR / renderer)
    # the one aggregate a renderer still reads directly
    five = FIGURE_DIR.parent / "results" / "summary" / "five_arms.json"
    if stem in RENDERED_BY["render_results.py"] and five.exists():
        out.append(five)
    return [p for p in out if p.exists()]


def check_freshness(pdfs: list[Path]) -> None:
    """Refuse to write a manifest for a figure older than what produced it.

    A manifest measures include widths off the rendered PDF. If the PDF is
    stale the width is honest about a figure nobody has drawn since the data
    moved, which is exactly the kind of quietly-wrong artefact this project
    keeps finding.
    """
    stale: list[tuple[Path, Path]] = []
    for pdf in pdfs:
        for src in sources_for(pdf.stem):
            if pdf.stat().st_mtime < src.stat().st_mtime:
                stale.append((pdf, src))
                break
    if not stale:
        return
    root = FIGURE_DIR.parent
    lines = ["STALE FIGURES — manifest not written.", ""]
    for pdf, src in sorted(stale):
        lines.append(f"  {pdf.name}")
        lines.append(f"      older than {src.relative_to(root)}")
    lines += ["", "  Re-render, then run this again:", "",
              "    uv run python figures/render_results.py",
              "    uv run python figures/render_theory.py",
              "    uv run python figures/render_intro.py"]
    raise SystemExit("\n".join(lines))


def main() -> None:
    check_freshness(sorted(FIGURE_DIR.glob("fig_*.pdf")))
    rows = []
    for pdf in sorted(FIGURE_DIR.glob("fig_*.pdf")):
        width = pdf_width_cm(pdf)
        if width is None:
            continue
        spec, note = include_spec(width)
        rows.append((pdf.stem, width, spec, note))

    lines = [
        "# FIGURES_MANIFEST.md",
        "# Generated by `make_manifest.py`. Do not edit by hand.",
        "",
        "Include widths measured from the rendered PDFs, so they cannot drift",
        "from what was drawn. See `thesis_writing/FIGURES.md` §2 and §8.",
        "",
        f"Text block: **{TEXT_WIDTH_CM:.1f} cm** (`includes.tex:20`).",
        "",
        "| figure | natural width | include at | note |",
        "|---|---|---|---|",
    ]
    for stem, width, spec, note in rows:
        lines.append(f"| `{stem}.pdf` | {width:.2f} cm | `{spec}` | {note} |")

    lines += ["", "---", "", "## Ready-to-paste floats", ""]
    for stem, _, spec, _ in rows:
        label = LABELS.get(stem, f"fig:{stem.replace('_', '-')}")
        lines += [
            "```latex",
            "\\begin{figure}[htb]",
            "  \\centering",
            f"  \\includegraphics[width={spec}]{{figures/{stem}.pdf}}",
            "  \\caption{TODO — state the finding, end with a provenance tag.}",
            f"  \\label{{{label}}}",
            "\\end{figure}",
            "```",
            "",
        ]

    out = FIGURE_DIR / "FIGURES_MANIFEST.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out.name} ({len(rows)} figures)")


if __name__ == "__main__":
    main()
